### PR TITLE
Production merge

### PR DESCRIPTION
**Pull request by shivankacker**
Dependent on https://github.com/coronasafe/ayushma/pull/519

---

### Changes
- Adds support for GPT-4o models
- Adds support for multi-model tests

### Please test:
- Chat functionality and quality of responses. (due to backend change for vector storage)
- If tests are executing correctly with multiple models

### CODE REVIEW

**Comment by tomahawk-pilot** [comment]
#### 📝 Changed routes:


| [**/**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/) | [**/layout-client**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/layout-client) |
|:-:|:-:|
|<a href="https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/A7J1UEsETwBdAkpGuBdID6IjOic6xm2zyQcd-qZbLrVDYof8A7yJAUrpccPKjRFmUsM8wb92kOVb1_SCYlQcTA.png">(view full size)</a> |<a href="https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/layout-client">Screenshot of /layout-client</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/fdFx90jlTfYzO_nOH1HyjIO4SIMUPurbOJDPGCkWSU9d33yAW1XEuSkSr5j1A8ydH6ALEQ4Uvq9tP2121t0VTQ.png">(view full size)</a> |



| [**/profile**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/profile) | [**…ect_id\]/chat/\[chat_id\]**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/project/[project_id]/chat/[chat_id]) |
|:-:|:-:|
|<a href="https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/profile">Screenshot of /profile</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Uk5Mg2LiTI2v3D2S4g_r1R-Lkmz5PYWAQajIwtG53GVmBWGPZls6GarzcJ5kSUUZCoR_WJ-DAPhjF3yaghkjTQ.png">(view full size)</a> |<a href="https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/project/[project_id]/chat/[chat_id]">Screenshot of /project/[project_id]/chat/[chat_id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3ldWhgkEeSpQgJEw6yOfCfut6LQImtMlVphZrohn3UMW_yYvIcZMzpLXhLAch8o4nr_y5g0fV3nxbc5JFimLgA.png">(view full size)</a> |



| [**/project/\[project_id\]**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/project/[project_id]) | [**/admin**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin) |
|:-:|:-:|
|<a href="https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/project/[project_id]">Screenshot of /project/[project_id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3H6JnyiCDP4n3RoEzAeKIeXKbXiCEYcobnddOSNXQ6XLR290YJwnet0AxVNcDK0qZKaU0JpKQzK2QRTlL6tlOA.png">(view full size)</a> |<a href="https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin">Screenshot of /admin</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/1DTg64BwSnToTIjk4L30ul44qi9KyuQARvXrTEvhVhdfLAYg3w-lYv5THF-NofOnUaXPiT6Y6_Z6A_A46o6x5w.png">(view full size)</a> |



And 12 other routes:
- [**/admin/projects/\[project_id\]/chats/\[chat_id\]**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/projects/[project_id]/chats/[chat_id])
- [**/admin/projects/\[project_id\]/chats**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/projects/[project_id]/chats)
- [**/admin/projects/\[project_id\]/documents/new**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/projects/[project_id]/documents/new)
- [**/admin/projects/\[project_id\]**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/projects/[project_id])
- [**/admin/projects/new**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/projects/new)
- [**/admin/tests/\[testsuite_id\]**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/tests/[testsuite_id])
- [**/admin/tests/\[testsuite_id\]/runs/\[testrun_id\]**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/tests/[testsuite_id]/runs/[testrun_id])
- [**/admin/tests/new**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/tests/new)
- [**/admin/tests**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/tests)
- [**/admin/users/\[username\]**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/users/[username])
- [**/admin/users**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/admin/users)
- [**/home**](https://ayushma-4gz8htrjo-ohcnetwork.vercel.app/home)

1 deleted route:
- **/chatbot**

Commit dfe487e08338f450fb553221914d44a4f964ee9f (https://ayushma-4gz8htrjo-ohcnetwork.vercel.app).

**Comment by gigincg** [comment]
@aparnacoronasafe Can you test the updates to Ayushma, ready for Production Release

**Comment by samholics** [comment]
- [ ]  Not able to register new users on staging. ( ERROR for site owner:
Invalid domain for site key  error is showing on Recaptcha field) 
 WhatsApp Image 2024-09-03 at 17 38 46_d26fdaed

- [ ] when stop recording without any audio inputs, its shows "You" or "Thanks for Watching" feedbacks
WhatsApp Image 2024-09-03 at 17 37 41_1983eae7
WhatsApp Image 2024-09-03 at 17 10 41_dd2d277a

**Comment by samholics** [comment]
Asked question : )My patient in Ards and suspected sepsis has MAP less than 65 and I gave him 
Piperacillin tazobactam. What more antibiotics to be given if he still has fever on the 3rd day?  

Answer - (2) cefepime (2 g q8h), or (3) 
meropenem (1 g q8h) or imipenem-cilastatin (0.5 g q6h). 
If the patient is allergic to ß-lactam antibiotics, use (1) aztreonam (2 g q8h) or (2) ciprofloxacin (400 mg 
q12h) or 
levofloxacin (750 mg q24h). Add vancomycin (loading dose of 25-30 mg/kg, then 15-20 mg/kg q8-12h) to 
each of the above regimens.

- [ ]  Initial two times gave correct response as the answer mentioned above. but later Medicine name in the question transcripting to others and gave no response. (same question)
- [ ] Audio output and the Green color highlighting of the text is not matching. text highlight is slower than audio. 
- [ ] for some scenarios transcription takes longer time than expected
- [ ] Transcription Loading Icon should be more evident. users might think the page is frozen while its transcripting. 
https://drive.google.com/file/d/1zTf9_-iZVFcQ01iyEtQUy6xkvm6BmA6h/view?usp=drivesdk

**Comment by samholics** [comment]
Tested all the FAQs in PPH section and its all responding well. 
note: Different Pronunciation of medical terms may result in NO results. (eg: PPH captured as BPH, piperacillin-tazobactam came as bifuraxilin lasopectum etc. )

**Comment by shivankacker** [comment]
@samholics 

1 - Issue with recaptcha has been solved.
2 - Issue with empty audio is due to whisper hallucinating. Although model hallucinations are hard to prevent, I will cover it up in https://github.com/ohcnetwork/ayushma/issues/521
3 - If the response was correct the first 2 times, an error on the third time would be due to hallucinations in the model. This should be a rare occurrence. If this happens often, we can cover it up later on.
4 - The audio highlights don't match currently. I will check and verify if it is possible to match them.
5 - Likely due to server load at OpenAI's end. I will investigate
6 - What do you suggest for making it more evident?

@gigincg I think we can merge to production as none of the pointed out issues pertain to the vector db change. They can be taken up later.

**Pull request merged**
